### ISSUE TITLE
Rtools intallation issue package 'lfmm'

### ISSUE THREAD

**Issue by nicholasprice79** [r-windows/checks#64]
Hi,

I am trying to  install this program "lfmm" and I think Rtools is giving me an issue. These are the output lines. 

> devtools::install_github("bcm-uga/lfmm")
Downloading GitHub repo bcm-uga/lfmm@master
Your system is ready to build packages!
  
  
  
   checking for file 'C:\Users\Nicholas Price\AppData\Local\Temp\Rtmp0KJylp\remotes31c8338a2773\bcm-uga-lfmm-5411c35/DESCRIPTION' ...
  
   checking for file 'C:\Users\Nicholas Price\AppData\Local\Temp\Rtmp0KJylp\remotes31c8338a2773\bcm-uga-lfmm-5411c35/DESCRIPTION' ... 
  
√  checking for file 'C:\Users\Nicholas Price\AppData\Local\Temp\Rtmp0KJylp\remotes31c8338a2773\bcm-uga-lfmm-5411c35/DESCRIPTION' (354ms)

  
  
  
-  preparing 'lfmm':
   checking DESCRIPTION meta-information ...
  
   checking DESCRIPTION meta-information ... 
  
√  checking DESCRIPTION meta-information
-  cleaning src

  
  
  
-  checking for LF line-endings in source and make files and shell scripts

  
  
  
-  checking for empty or unneeded directories

  
  
  
-  looking to see if a 'data/datalist' file should be added

  
  
  
-  building 'lfmm_0.0.tar.gz'

  
   

Installing package into ‘C:/Users/Nicholas Price/Documents/R/win-library/3.6’
(as ‘lib’ is unspecified)
* installing *source* package 'lfmm' ...
** using staged installation
** libs
c:/Rtools/mingw_64/bin/g++  -I"C:/PROGRA~1/R/R-3.6.1/include" -DNDEBUG  -I"C:/Program Files/R/R-3.6.1/library/Rcpp/include" -I"C:/Program Files/R/R-3.6.1/library/RcppEigen/include"        -O2 -Wall  -mtune=generic -c RcppExports.cpp -o RcppExports.o
c:/Rtools/mingw_64/bin/g++  -I"C:/PROGRA~1/R/R-3.6.1/include" -DNDEBUG  -I"C:/Program Files/R/R-3.6.1/library/Rcpp/include" -I"C:/Program Files/R/R-3.6.1/library/RcppEigen/include"        -O2 -Wall  -mtune=generic -c helpers.cpp -o helpers.o
c:/Rtools/mingw_64/bin/g++  -I"C:/PROGRA~1/R/R-3.6.1/include" -DNDEBUG  -I"C:/Program Files/R/R-3.6.1/library/Rcpp/include" -I"C:/Program Files/R/R-3.6.1/library/RcppEigen/include"        -O2 -Wall  -mtune=generic -c tess3.cpp -o tess3.o
c:/Rtools/mingw_64/bin/g++ -shared -s -static-libgcc -o lfmm.dll tmp.def RcppExports.o helpers.o tess3.o -LC:/PROGRA~1/R/R-3.6.1/bin/x64 -lR
installing to C:/Users/Nicholas Price/Documents/R/win-library/3.6/00LOCK-lfmm/00new/lfmm/libs/x64
** R
** data
*** moving datasets to lazyload DB
** inst
** byte-compile and prepare package for lazy loading
Fatal error: cannot open file 'C:\Users\Nicholas': No such file or directory

ERROR: lazy loading failed for package 'lfmm'
* removing 'C:/Users/Nicholas Price/Documents/R/win-library/3.6/lfmm'
Error: Failed to install 'lfmm' from GitHub:
  (converted from warning) installation of package ‘C:/Users/Nicholas Price/AppData/Local/Temp/Rtmp0KJylp/file31c87df71e2f/lfmm_0.0.tar.gz’ had non-zero exit status
>

**Comment by jeroen** [comment]
You're posting this in the wrong repository. This repo is for issues with the new toolchain.

Either way because you are here now: it seems the problem is the space in your windows username. You should test if this is still a problem with the latest [R-devel](https://cran.r-project.org/bin/windows/base/rdevel.html) releases. If this bug still exists you should post it to the [r-devel mailing list](https://stat.ethz.ch/mailman/listinfo/r-devel).
