### ISSUE TITLE
error: mingw32 database is inconsistent

### ISSUE THREAD

**Issue by guihigashi** [r-windows/checks#66]
When search for a package that contains a file, ie `pacman -Fs glpk.h`, I get this error message, `error: mingw32 database is inconsistent: version mismatch on package mingw-w64-i686-binutils` and the results
```
mingw32/mingw-w64-i686-glpk 4.65-1
    mingw32/include/glpk.h
mingw64/mingw-w64-x86_64-glpk 4.65-1
    mingw64/include/glpk.h
```
Meaning this error doesn't prevent me from getting the results, but it's probably something to fix

**Comment by jeroen** [comment]
Thanks this should be fixed now (add the `y` flag to refresh):

```
pacman -Fsy glpk.h
```
