### ISSUE TITLE
lidR

### ISSUE THREAD

**Issue by jeroen** [r-windows/checks#82]
```
  -- 1. Failure: tree_detection LMF works with a RasterLayer (@test-tree_detection
  dim(ttops@data) not equal to c(158, 2).
  1/2 mismatches
  [1] 157 - 158 == -1
```

**Comment by jeroen** [comment]
Problem also appears with openblas build of R.

**Comment by jeroen** [comment]
Problem still appears after lapack update in base R.

**Comment by jeroen** [comment]
Seems to be fixed by compiling `raster` with `-O2 -msse2 -mfpmath=sse`.

**Comment by Jean-Romain** [comment]
Here the developer of `lidR`. The problem does not come from `raster`. I spent my day searching the problem. I was not able to spot it but I fixed it in a way that is not understandable to me.

I appended an `Rprintf` in a condition that will never be true after [line 990](https://github.com/Jean-Romain/lidR/blob/devel/src/LAS.cpp#L990):

```cpp
if (cell == raster.size() + 1) // Never true
    Rprintf("x = %lf, y = %lf\n", x, y);
```

If I print `x` and `y` the output is correct. Thus I was not able to debug. If I do not print I do not know the content of the variable. If I print the content is correct. Consequently I added this and it is ok on CRAN.

```cpp
#ifdef _WIN32
#ifdef __MINGW32__
#ifdef __GNUC__
#if __GNUC__ >= 8
if (cell == raster.size() + 1) Rprintf("x = %lf, y = %lf\n", x, y);
#endif
#endif
#endif
#endif
```

I hope this may help. If you understand something please let me know.

**Comment by jeroen** [comment]
Does the package now pass if you submit it to `R-devel ATC (alternative toolchain)` on [winbuilder](http://win-builder.r-project.org/upload.aspx)?

**Comment by Jean-Romain** [comment]
Yes it passes CRAN checks on ATC

**Comment by jeroen** [comment]
OK if that works, it would be helpful if you submit the workaround to cran. 

This is a very strange bug, I think it is a result of new optimizations in recent versions of gcc that affect rounding behavior of edge cases on 32-bit architectures. Because 32-bit is mostly obsolete, it is no longer a priority for gcc developers.

I think you'll see the same problem on GCC 8 on 32-bit linux.

**Comment by Jean-Romain** [comment]
I will submit soon (in few days). It indeed affects only some edge cases (which one? I don't now). In my case it affected 58 values out of 8000+. I'm don't know how to compile on a package for 32 bit with linux without a 32 bit machine so I don't know if it is reproducible. 

Do you think I should remove `#ifdef _WIN32` and `#ifdef __MINGW32__` for something more generic? If yes what is the best?

**Comment by jeroen** [comment]
Indeed that is the problem, nobody runs 32 bit systems anymore, except for windows :-) Therefore I think your current workaround is fine. But indeed you could remove `#ifdef _WIN32` and `#ifdef __MINGW32__ ` to also fix the problem on other systems.

**Comment by jeroen** [comment]
Fixed on CRAN by switching to sse2
