### ISSUE TITLE
nlmixr, RxODE

### ISSUE THREAD

**Issue by jeroen** [r-windows/checks#84]
On Winbuilder:

```
Error building model

Warning message:
In system(cmd) : 'make' not found
```

Seems to work fine on my machine. Must be PATH issue on winbuilder.

**Comment by mattfidler** [comment]
@jeroen if there is something that needs to be changed on my end let me know.

**Comment by jeroen** [comment]
I'm not sure why it doesn't work on winbuilder. Where does RxODE look for `make`?

**Comment by mattfidler** [comment]
It doesn't look for make;  It executes:

```sh
R CMD SHLIB cfile.c
```

To create the C file.  In theory it uses `BINPREF`, though perhaps it looks first so see if `c:\Rtools` is present and uses the setup binpref from there.

**Comment by mattfidler** [comment]
To be more clear;  On windows, RxODE checks to see if `gcc` is present in the `BINPREF` directory. If so it assumes everything is OK and doesn't look for it in other semi-standard places.

**Comment by jeroen** [comment]
Very strange. On my computer it works fine with gcc 8 but somehow on winbuilder not. One difference is that winbuilder has both the old rtools35 and the new rtools40 installed, could be picking up on the wrong one?

Can you point me to the place where `R CMD SHLIB` is called which results in the `make` warning?

Maybe you can add some more verbose output and then submit to winbuilder: http://win-builder.r-project.org/upload.aspx and check the log files what is happening ...

**Comment by mattfidler** [comment]
It's probably picking up the wrong rtools.  I will probably have to submit
to the new tool chain to see what's going on

**Comment by jeroen** [comment]
Seems fixed on CRAN.

**Comment by mattfidler** [comment]
Thanks @jeroen
